[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
dirs = "6.0.0"
handlebars = "6.3.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
